feat: adicionei a traducao fr e es da issue #53 e adicionei as metricas de open graph para melhorar o seo
angolaosc/angolaosc.org pull request #70
Opened 2024-02-13 17:23 UTC by euotiniel

## 1

Comecei por adicionar a metatags para ajudar no SEO do website, onde além de codificar, criei uma imagem de fundo que será exibida sempre que o website for partilhado.

código:

```JS
export const metadata: Metadata = {
  metadataBase: new URL("https://aosc.social/"),
  title: {
    default: "Angola Open Source Community",
    template: "",
  },
  description:
    "Criando um impacto significativo na inovação tecnológica do país",
  openGraph: {
    title: "Angola Open Source Community",
    description:
      "Criando um impacto significativo na inovação tecnológica do país.",
    url: "https://aosc.social/",
    siteName: "Angola Open Source Community",
    locale: "pt_AO",
    type: "website",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  twitter: {
    title: "Angola Open Source Community",
    card: "summary_large_image",
  },
};
```

Cover

![Um software livre não é necessariamente Open-source_ Entendendo as diferenças (2)](https://github.com/angolaosc/aosc.social/assets/93485038/76046dbc-0fe6-4574-a378-44a076e02fd1)

> Considerem modificar a imagem.

Se observarmos, até agora as analises são apresentadas assim: https://www.opengraph.xyz/url/https%3A%2F%2Faosc.social%2F

## 2

Resolvi a Issue #53 , adicionando a tradução de Espanhol e Frances.

2024-02-21 21:52 UTC, antonio-pedro99 commented
@euotiniel Obrigado pela PR, o @Afranioalves irá revisar!

2024-03-04 09:32 UTC, Afranioalves approved these changes
777- muito obrigado pela a criação do cover do site

2024-03-04 09:36 UTC, Afranioalves approved these changes
777- @euotiniel 🙌👋

2024-03-04 09:40 UTC, Afranioalves approved these changes
777- @euotiniel  obrigado pela contribuição, isso foi uma mega contribuição, vai ajudar bastante no SEO do site...

2024-03-07 15:45 UTC, antonio-pedro99 requested changes
Ola @euotiniel, mais uma vez, muito obrigado pela contribuição e pelo tempo.

Depois da revisão do Afrânio, tenho mais alguns comentários.

### Pull Request
Na próxima vez, será mais fácil enviar uma PR para cada funcionalidade que estiver a sugerir. 

### Tradução

Muito obrigado por contribuir com as traduções em espanhol e francês, mas para aceitar essas traduções, precisamos que algum falante nativo ou fluente faça a revisão dessas traduções. Eu deixei alguns comentários sobre o uso de espanhol e português na mesma frase, o que deixa-me confuso :(. Então, vamos procurar na comunidade algum falante de espanhol e francês para revisar essas traduções e só depois podemos seguir.

### Você mesmo decida

Então, encontrar revisores para as traduções poderá levar um tempo, então você mesmo decida se vais separar a Pull Request por funcionalidades: 
** Tradução(resolvendo a issue #53)
** Melhorando o SEO do site.

Mais uma vez, muito obrigado pela PR.

2024-03-07 15:45 UTC, antonio-pedro99 commented on src/app/components/header/data.ts
> +    text: i18n.t("nav.link_1"),
Qual é a razão dessa mudança?

2024-03-07 15:45 UTC, antonio-pedro99 commented on src/app/components/header/data.ts
> +    language: "Frances",
O correcto seria Francês?

2024-03-07 15:45 UTC, antonio-pedro99 commented on src/app/globals.css
> +
NMHO(Na minha humilde opnião), não podemos deixar códigos comentados.

2024-03-07 15:45 UTC, antonio-pedro99 commented on src/translate/languages/es.ts
Esse ficheiro tem muito português com Espanhol.

2024-03-07 15:45 UTC, antonio-pedro99 commented on src/translate/languages/es.ts
> +              info: 'Próximo evento: .NET Conf Luanda 2023 en Luanda el 10 de febrero de 2024',
Português com espanhol.

2024-03-07 15:45 UTC, antonio-pedro99 commented on src/translate/languages/es.ts
> +              title :`Creando un impacto significativo en la innovación tecnológica en Angola.`,
Português com espanhol :)

2024-03-07 15:45 UTC, antonio-pedro99 commented on src/translate/languages/fr.ts
Bacana! Mas não sou fluente em francês, então não tenho como revisar :)

2024-03-07 15:45 UTC, antonio-pedro99 commented on src/translate/languages/pt.ts
> +                smallText: 'Um pequeno texto'
Qual é a razão em manter esses textos aqui?

2024-03-08 00:03 UTC, trupakufi commented on src/app/globals.css
> +
Concordo.

2024-03-08 00:05 UTC, trupakufi commented on src/app/components/header/data.ts
> +    language: "Frances",
E no English Inglês ?

2024-03-08 00:07 UTC, trupakufi commented on src/app/components/header/data.ts
> +    text: i18n.t("nav.link_1"),
Essas mudanças são resultado das configurações de formatação do ambiente dele.

2024-03-08 00:08 UTC, trupakufi commented on src/app/components/header/index.tsx
> +  const [language, setLanguage] = useState<any>("pt-BR");
Porquê que aqui o useState é do type any se ele recebe uma string ?

2024-03-08 00:08 UTC, trupakufi commented on src/app/components/header/index.tsx
> +    console.log("Olhe as linguagens", languages);
Depois de testar localmente acho que seria bom eliminar os logs.

2024-03-08 00:09 UTC, trupakufi commented on src/app/components/header/index.tsx
>      switch (language) {
E se ao invés de um Switch usássemos um Object?

2024-03-08 00:14 UTC, trupakufi reviewed
@euotiniel Bom trabalho, seria bom analisar os aspectos mencionados pelo @antonio-pedro99

2024-03-10 17:23 UTC, Afranioalves commented on src/app/components/header/index.tsx
> +  const [language, setLanguage] = useState<any>("pt-BR");
777- realmente seria <string> em vez de <any>

2024-03-12 14:40 UTC, antonio-pedro99 commented
@euotiniel Olá, já decidiste se vais separar a PR ou não? hehehe

2024-04-09 20:38 UTC, antonio-pedro99 commented
@euotiniel ola, alguma novidade?

2024-04-10 13:32 UTC, euotiniel commented
Vou separar, ainda hoje envio o PR do SEO.

2024-04-10 14:04 UTC, euotiniel commented
Conhceço uma cara fluente em françês, mas não é dev. Vou ver se ele consegue revisar a tradução em françês.

2024-07-22 20:06 UTC, closed without merging

2024-07-22 20:06 UTC, antonio-pedro99 commented
> Conheço uma cara fluente em francês, mas não é dev. Vou ver se ele consegue revisar a tradução em francês.

Obrigado pela contribuição. Vou esperar a PR separada sobre o SEO. Por enquanto vou fechar essa.